-- THE GUARDIAN — initial schema
-- pgvector must exist before any vector(...) column.
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Properties (the core catalogue).
CREATE TABLE IF NOT EXISTS properties (
  id                SERIAL PRIMARY KEY,
  project_name      TEXT NOT NULL,
  developer_name    TEXT,
  location          TEXT,
  micro_location    TEXT,
  city              TEXT,
  property_type     TEXT,            -- residential | commercial
  bhk               TEXT,            -- e.g. "2 BHK"
  configuration     TEXT,            -- free-form config text
  min_price         BIGINT,          -- INR
  max_price         BIGINT,          -- INR
  price_text        TEXT,            -- original price string as imported
  carpet_area       TEXT,
  possession_status TEXT,            -- ready | under-construction
  possession_date   TEXT,
  rera_number       TEXT,
  amenities         JSONB DEFAULT '[]'::jsonb,
  nearby_landmarks  JSONB DEFAULT '[]'::jsonb,
  suitable_for      JSONB DEFAULT '[]'::jsonb,
  raw_data          JSONB DEFAULT '{}'::jsonb,  -- unmapped import columns
  source_file       TEXT,
  metadata          JSONB DEFAULT '{}'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Upsert key for re-imports (project + micro-location identifies a listing).
CREATE UNIQUE INDEX IF NOT EXISTS properties_project_microloc_uniq
  ON properties (project_name, COALESCE(micro_location, ''));

-- 2. Property documents (PDF chunks + embeddings for RAG).
CREATE TABLE IF NOT EXISTS property_documents (
  id            SERIAL PRIMARY KEY,
  property_id   INTEGER REFERENCES properties(id) ON DELETE SET NULL,
  chunk_text    TEXT NOT NULL,
  embedding     vector(1536),
  document_type TEXT,            -- brochure | price-list | other
  metadata      JSONB DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS property_documents_property_id_idx
  ON property_documents (property_id);

-- 3. Chat sessions (one per widget visitor).
CREATE TABLE IF NOT EXISTS chat_sessions (
  id         TEXT PRIMARY KEY,     -- uuid generated by the widget
  page_url   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Messages (full transcript per session).
CREATE TABLE IF NOT EXISTS messages (
  id         SERIAL PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  role       TEXT NOT NULL,        -- user | assistant
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS messages_session_id_idx
  ON messages (session_id, created_at);

-- 5. Leads (slot state + qualification per session).
CREATE TABLE IF NOT EXISTS leads (
  id                 SERIAL PRIMARY KEY,
  session_id         TEXT UNIQUE REFERENCES chat_sessions(id) ON DELETE CASCADE,
  name               TEXT,
  phone              TEXT,
  email              TEXT,
  prefs              JSONB DEFAULT '{}'::jsonb,   -- collected slots
  matched_properties JSONB DEFAULT '[]'::jsonb,
  lead_score         INTEGER NOT NULL DEFAULT 0,  -- 0..100
  status             TEXT NOT NULL DEFAULT 'new',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
